name: "StarMc"
lang: "pl"
token: "1191766434905333902" # Discord bot token
interval: 10000 # ms
server: "play.starmcop.fun"

message:
  enabled: true
  channel: "" # Channel id
status:
  enabled: true
